// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../library_db.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `play_count_metadata_key`, `record_history_row`

Future<void> incrementPlayCount({
  required String indexPath,
  required String path,
}) => RustLib.instance.api.crateApiLibraryDbPlayCountsIncrementPlayCount(
  indexPath: indexPath,
  path: path,
);

Future<List<PlayCountEntry>> getTopPlayed({
  required String indexPath,
  required int limit,
}) => RustLib.instance.api.crateApiLibraryDbPlayCountsGetTopPlayed(
  indexPath: indexPath,
  limit: limit,
);

Future<PlatformInt64> getPlayCount({
  required String indexPath,
  required String path,
}) => RustLib.instance.api.crateApiLibraryDbPlayCountsGetPlayCount(
  indexPath: indexPath,
  path: path,
);

Future<List<PlayCountEntry>> exportPlayCounts({required String indexPath}) =>
    RustLib.instance.api.crateApiLibraryDbPlayCountsExportPlayCounts(
      indexPath: indexPath,
    );

/// 按路径或唯一的标题、艺术家、专辑组合写回播放次数；不新建曲库行。
/// `overwrite` 为 false 时取本机与传入值的较大值，为 true 时直接使用传入值。
Future<int> importPlayCounts({
  required String indexPath,
  required List<PlayCountEntry> entries,
  required bool overwrite,
}) => RustLib.instance.api.crateApiLibraryDbPlayCountsImportPlayCounts(
  indexPath: indexPath,
  entries: entries,
  overwrite: overwrite,
);

/// 导出全部播放流水，按路径分组；包含已不在曲库的路径，便于删歌后恢复。
Future<List<PlayHistoryEntry>> exportPlayHistory({required String indexPath}) =>
    RustLib.instance.api.crateApiLibraryDbPlayCountsExportPlayHistory(
      indexPath: indexPath,
    );

/// 播放流水聚合：趋势按日、收听节律按小时、报告按星期×小时。
/// 日期/小时按本机时区（SQLite localtime）分桶。
Future<PlayHistoryStats> getPlayHistoryStats({required String indexPath}) =>
    RustLib.instance.api.crateApiLibraryDbPlayCountsGetPlayHistoryStats(
      indexPath: indexPath,
    );

/// 导入播放流水。`overwrite` 为 true 时先清空本机流水；
/// merge 模式按 (路径, 时间戳) 去重追加。不校验路径是否在曲库中。
Future<int> importPlayHistory({
  required String indexPath,
  required List<PlayHistoryEntry> entries,
  required bool overwrite,
}) => RustLib.instance.api.crateApiLibraryDbPlayCountsImportPlayHistory(
  indexPath: indexPath,
  entries: entries,
  overwrite: overwrite,
);
