// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cache`, `deserialize_metadata`, `download_index_text`, `http_get`, `parse_index`, `resolve_index`, `score_entry`, `should_refresh_index`, `write_index_cache`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedIndex`, `IndexEntry`, `Metadata`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`

Future<List<AmllSearchItem>> amllSearchLyrics(
        {required String keyword,
        required int page,
        required int pageSize,
        required String cacheDir}) =>
    RustLib.instance.api.crateApiAmllTtmlAmllSearchLyrics(
        keyword: keyword, page: page, pageSize: pageSize, cacheDir: cacheDir);

Future<String?> amllGetTtml({required String id}) =>
    RustLib.instance.api.crateApiAmllTtmlAmllGetTtml(id: id);

Future<void> amllClearCache() =>
    RustLib.instance.api.crateApiAmllTtmlAmllClearCache();

class AmllSearchItem {
  final String id;
  final String title;
  final String artist;
  final String album;
  final double score;

  const AmllSearchItem({
    required this.id,
    required this.title,
    required this.artist,
    required this.album,
    required this.score,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AmllSearchItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          score == other.score;
}
