// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_extract_colors_from_image`, `allocate_dominant_palette_slots`, `contrast`, `extract_colors_from_decoded_image`, `extract_mesh_colors_from_decoded_image`, `hsl_to_rgb`, `hue_to_rgb`, `is_meaningful_candidate`, `lab_distance_squared`, `pack_argb`, `rgb_to_hsl`, `select_palette_candidates`, `soften_color_for_background`, `spread_palette_candidates`, `visual_sample_weight`

Future<Uint32List> extractColorsFromImage({
  required List<int> imageBytes,
  required int numColors,
}) => RustLib.instance.api.crateApiColorExtractionExtractColorsFromImage(
  imageBytes: imageBytes,
  numColors: numColors,
);
