// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `atomic_write_with_replace`, `audio_identity`, `backfill_audio_identities`, `cover_access_timestamp`, `cover_source_signature`, `cover_tier_exceeds_limit`, `cover_tier`, `ensure_database_layout`, `ensure_index_source_current`, `file_source_signature`, `has_database_layout_marker`, `index_source_signature`, `index_temp_file`, `init_schema`, `legacy_sqlite_path`, `metadata_match_key`, `migrating_sqlite_path`, `normalize_identity_part`, `open_connection`, `open_raw_connection`, `path_lookup_key`, `prune_cover_thumbnail_tier`, `read_cover_thumbnail`, `read_current_index_snapshot`, `rebuild_database_from_legacy`, `remove_database_file`, `remove_database_files`, `replace_file_atomically`, `should_rebuild_database`, `sqlite_path`, `sqlite_sidecar_path`, `stable_file_id`, `stored_index_source_signature`, `unique_play_count`, `with_cover_connection`, `with_index_write_lock`, `write_cover_thumbnail`, `write_index_json`, `write_index_snapshot_with`, `write_index_snapshot`, `write_index_value_to_sqlite`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioIdentity`, `CoverTier`, `IndexFolderSnapshot`, `IndexSnapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<Uint8List?> getCachedCover({
  required String indexPath,
  required String path,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiLibraryDbGetCachedCover(
  indexPath: indexPath,
  path: path,
  width: width,
  height: height,
);

Future<void> incrementPlayCount({
  required String indexPath,
  required String path,
}) => RustLib.instance.api.crateApiLibraryDbIncrementPlayCount(
  indexPath: indexPath,
  path: path,
);

Future<List<PlayCountEntry>> getTopPlayed({
  required String indexPath,
  required int limit,
}) => RustLib.instance.api.crateApiLibraryDbGetTopPlayed(
  indexPath: indexPath,
  limit: limit,
);

Future<PlatformInt64> getPlayCount({
  required String indexPath,
  required String path,
}) => RustLib.instance.api.crateApiLibraryDbGetPlayCount(
  indexPath: indexPath,
  path: path,
);

Future<void> migrateIndexJsonToSqlite({required String indexPath}) => RustLib
    .instance
    .api
    .crateApiLibraryDbMigrateIndexJsonToSqlite(indexPath: indexPath);

Future<List<IndexFolder>> readIndexFromSqlite({required String indexPath}) =>
    RustLib.instance.api.crateApiLibraryDbReadIndexFromSqlite(
      indexPath: indexPath,
    );

class IndexAudio {
  final String title;
  final String artist;
  final String album;
  final String? albumArtist;
  final int track;
  final int disc;
  final BigInt duration;
  final int? bitrate;
  final int? sampleRate;
  final String path;
  final BigInt modified;
  final BigInt created;
  final String? by;
  final PlatformInt64 playCount;

  const IndexAudio({
    required this.title,
    required this.artist,
    required this.album,
    this.albumArtist,
    required this.track,
    required this.disc,
    required this.duration,
    this.bitrate,
    this.sampleRate,
    required this.path,
    required this.modified,
    required this.created,
    this.by,
    required this.playCount,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      track.hashCode ^
      disc.hashCode ^
      duration.hashCode ^
      bitrate.hashCode ^
      sampleRate.hashCode ^
      path.hashCode ^
      modified.hashCode ^
      created.hashCode ^
      by.hashCode ^
      playCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexAudio &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          track == other.track &&
          disc == other.disc &&
          duration == other.duration &&
          bitrate == other.bitrate &&
          sampleRate == other.sampleRate &&
          path == other.path &&
          modified == other.modified &&
          created == other.created &&
          by == other.by &&
          playCount == other.playCount;
}

class IndexFolder {
  final String path;
  final BigInt modified;
  final BigInt latest;
  final List<IndexAudio> audios;

  const IndexFolder({
    required this.path,
    required this.modified,
    required this.latest,
    required this.audios,
  });

  @override
  int get hashCode =>
      path.hashCode ^ modified.hashCode ^ latest.hashCode ^ audios.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexFolder &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          modified == other.modified &&
          latest == other.latest &&
          audios == other.audios;
}

class PlayCountEntry {
  final String path;
  final String title;
  final String artist;
  final String album;
  final PlatformInt64 playCount;

  const PlayCountEntry({
    required this.path,
    required this.title,
    required this.artist,
    required this.album,
    required this.playCount,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      playCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayCountEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          playCount == other.playCount;
}
