// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `aes_decrypt`, `aes_encrypt`, `eapi_params_encrypt`, `eapi_response_decrypt`, `generate_device_id`, `get_anonimous_username`, `get_cache_key`, `get_current_timestamp`, `get_params_header`, `get_request_header`, `pkcs7_pad`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CloudMusicResult`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

List<Map<String, String>> neSearch(
        {required String keyword, required int limit}) =>
    RustLib.instance.api.crateApiNeNeSearch(keyword: keyword, limit: limit);

String neLyric({required PlatformInt64 songId}) =>
    RustLib.instance.api.crateApiNeNeLyric(songId: songId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NetEaseCloud>>
abstract class NetEaseCloud implements RustOpaqueInterface {
  static Future<NetEaseCloud> default_() =>
      RustLib.instance.api.crateApiNeNetEaseCloudDefault();

  Future<LyricResult> getLyric({required PlatformInt64 songId});

  Future<void> init();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<NetEaseCloud> newInstance() =>
      RustLib.instance.api.crateApiNeNetEaseCloudNew();

  Future<List<Map<String, String>>> search(
      {required String keyword, required int limit});
}

class LyricContent {
  final int version;
  final String lyric;

  const LyricContent({
    required this.version,
    required this.lyric,
  });

  @override
  int get hashCode => version.hashCode ^ lyric.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricContent &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          lyric == other.lyric;
}

class LyricResult {
  final int code;
  final LyricContent? lrc;
  final LyricContent? tlyric;
  final LyricContent? yrc;
  final LyricContent? romalrc;
  final LyricUser? lyricUser;
  final LyricUser? transUser;

  const LyricResult({
    required this.code,
    this.lrc,
    this.tlyric,
    this.yrc,
    this.romalrc,
    this.lyricUser,
    this.transUser,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      lrc.hashCode ^
      tlyric.hashCode ^
      yrc.hashCode ^
      romalrc.hashCode ^
      lyricUser.hashCode ^
      transUser.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricResult &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          lrc == other.lrc &&
          tlyric == other.tlyric &&
          yrc == other.yrc &&
          romalrc == other.romalrc &&
          lyricUser == other.lyricUser &&
          transUser == other.transUser;
}

class LyricUser {
  final String nickname;

  const LyricUser({
    required this.nickname,
  });

  @override
  int get hashCode => nickname.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricUser &&
          runtimeType == other.runtimeType &&
          nickname == other.nickname;
}
