// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_jobs`, `analyze_with_cache`, `get`, `insert`, `memory_cache`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MemoryProfileCache`, `MemoryProfile`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<String> analyzeSmartTransitionTrack({
  required BigInt jobId,
  required String path,
  String? mediaId,
  required String libraryRoot,
}) => RustLib.instance.api.crateApiSmartTransitionAnalyzeSmartTransitionTrack(
  jobId: jobId,
  path: path,
  mediaId: mediaId,
  libraryRoot: libraryRoot,
);

bool cancelSmartTransitionAnalysis({required BigInt jobId}) => RustLib
    .instance
    .api
    .crateApiSmartTransitionCancelSmartTransitionAnalysis(jobId: jobId);

Future<String> planSmartTransitionJson({
  required String outgoingProfileJson,
  required String incomingProfileJson,
  required bool isGaplessCandidate,
  required bool isSameAlbum,
  required double userSpeed,
  required double pitch,
  required bool tempoAtCueAvailable,
  required double outgoingReplayGainDb,
  required double incomingReplayGainDb,
}) => RustLib.instance.api.crateApiSmartTransitionPlanSmartTransitionJson(
  outgoingProfileJson: outgoingProfileJson,
  incomingProfileJson: incomingProfileJson,
  isGaplessCandidate: isGaplessCandidate,
  isSameAlbum: isSameAlbum,
  userSpeed: userSpeed,
  pitch: pitch,
  tempoAtCueAvailable: tempoAtCueAvailable,
  outgoingReplayGainDb: outgoingReplayGainDb,
  incomingReplayGainDb: incomingReplayGainDb,
);

String smartTransitionAnalysisConfigJson() => RustLib.instance.api
    .crateApiSmartTransitionSmartTransitionAnalysisConfigJson();

Stream<String> initSmartTransitionEvents({required String bassDir}) => RustLib
    .instance
    .api
    .crateApiSmartTransitionInitSmartTransitionEvents(bassDir: bassDir);

void closeSmartTransitionEvents() =>
    RustLib.instance.api.crateApiSmartTransitionCloseSmartTransitionEvents();

String smartTransitionCapabilitiesJson({required String bassDir}) => RustLib
    .instance
    .api
    .crateApiSmartTransitionSmartTransitionCapabilitiesJson(bassDir: bassDir);

String armSmartTransitionJson({
  required String bassDir,
  required String requestJson,
}) => RustLib.instance.api.crateApiSmartTransitionArmSmartTransitionJson(
  bassDir: bassDir,
  requestJson: requestJson,
);

String cancelNativeSmartTransitionJson({
  required BigInt transitionId,
  required String reason,
}) =>
    RustLib.instance.api.crateApiSmartTransitionCancelNativeSmartTransitionJson(
      transitionId: transitionId,
      reason: reason,
    );

String adoptNativeSmartTransitionJson({required BigInt transitionId}) =>
    RustLib.instance.api.crateApiSmartTransitionAdoptNativeSmartTransitionJson(
      transitionId: transitionId,
    );

String nativeSmartTransitionSnapshotJson({required BigInt transitionId}) =>
    RustLib.instance.api
        .crateApiSmartTransitionNativeSmartTransitionSnapshotJson(
          transitionId: transitionId,
        );

bool acknowledgeNativeSmartTransition({required BigInt transitionId}) => RustLib
    .instance
    .api
    .crateApiSmartTransitionAcknowledgeNativeSmartTransition(
      transitionId: transitionId,
    );

String smartTransitionDiagnosticsJson() => RustLib.instance.api
    .crateApiSmartTransitionSmartTransitionDiagnosticsJson();
