// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_vibe`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SmartSortOutputJson`, `SortFeatureInput`, `SortInputEnvelope`

/// 输入为 SortInputEnvelope JSON；take_count 大于 0 时先按采样键分层抽样该数量再编排，
/// 输出的 order 始终指向原始输入下标。
Future<String> planSmartSortJson({
  required String payloadJson,
  required double climaxPosition,
  required double contrast,
  required BigInt takeCount,
  required double smoothness,
  required int outroStyle,
  required int taste,
}) => RustLib.instance.api.crateApiSmartSortPlanSmartSortJson(
  payloadJson: payloadJson,
  climaxPosition: climaxPosition,
  contrast: contrast,
  takeCount: takeCount,
  smoothness: smoothness,
  outroStyle: outroStyle,
  taste: taste,
);
