// 元数据剥离关键词表
const List<String> defaultExcludeKeywords = [
  '版权',
  '贝斯',
  '编曲',
  '策划',
  '出品',
  '词',
  '大提琴',
  '灯光设计',
  '第二小提琴',
  '第一小提琴',
  '发行',
  '翻唱',
  '封面',
  '钢琴/合成器演奏',
  '钢琴演奏',
  '歌名',
  '歌手',
  '工作室',
  '鼓',
  '合成器演奏',
  '合声',
  '合声编写',
  '和声',
  '和声编写',
  '和声演唱',
  '和音',
  '混缩',
  '混音',
  '吉他',
  '监制',
  '键盘',
  '乐队统筹',
  '乐器演奏',
  '乐团',
  '联合策划',
  '联合出品',
  '联合推广',
  '录/混音',
  '录音',
  '录音师',
  '录音室',
  '录音制作',
  '鸣谢',
  '母带',
  '配唱制作人',
  '企划',
  '曲',
  '设计',
  '特别鸣谢',
  '特别企划',
  '题记',
  '统筹',
  '推广',
  '维伴音乐',
  '文案',
  '弦乐',
  '弦乐编写',
  '弦乐监制',
  '弦乐录音师',
  '弦乐录音室',
  '项目统筹',
  '宣传',
  '宣推',
  '演唱',
  '艺术指导',
  '音乐项目总监',
  '音乐制作',
  '音乐制作发行',
  '音频编辑',
  '音乐编辑',
  '营销推广',
  '原唱',
  '制作发行',
  '制作公司',
  '制作人',
  '制作统筹',
  '制作团队',
  '制作助理',
  '中提琴',
  '专辑',
  '总策划',
  '总监制',
  '总企划',
  '作词',
  '作曲',
  // 日文
  '詞',
  '訳詞',
  '補作詞',
  '作詞',
  '作曲',
  '編曲',
  '歌',
  '歌唱',
  '演奏',
  'ギター',
  'ベース',
  'ドラム',
  'ピアノ',
  'ストリングス',
  'ホーン',
  'コーラス',
  'ミックス',
  'マスタリング',
  'プロデュース',
  'プロデューサー',
  'レコーディング',
  'エンジニア',
  '録音',
  '作編曲',
  '音楽プロデューサー',
  'サウンドプロデューサー',
  'ディレクター',
  'アレンジ',
  // 韩文
  '작사',
  '작곡',
  '편곡',
  '노래',
  '코러스',
  '기타',
  '베이스',
  '드럼',
  '피아노',
  '현악',
  '믹싱',
  '마스터링',
  '프로듀서',
  '녹음',
  '발매',
  '제작',
  '연주',
  '편성',
  '지휘',
  '건반',
  '타악기',
  '관현악',
  '합창',
  // 其他常见语言
  'pgm',
  'Paroles',
  'Musique',
  'Letra',
  'Testo',
  'Acknowledgement',
  'Additional Vocal by',
  'Arranged By',
  'Arrangement',
  'Arranger',
  'Art Director',
  'Artist',
  'Background Vocals by',
  'Backing Vocal',
  'Backing Vocal Arrangement',
  'Backing Vocals',
  'Backing Vocals Design',
  'Bass',
  'Cello',
  'Chief Producer',
  'Chref Planner',
  'Co-produced by',
  'Co-Producer',
  'Co-production',
  'Composed by',
  'Composer',
  'Copywriting',
  'Cover Design',
  'Design',
  'Distributed by',
  'Distribution',
  'Drums',
  'Executive Producer',
  'First Violin',
  'Guitar',
  'Guitars',
  'Jointly Produced by',
  'Lyricist',
  'Lyrics',
  'Lyrics & Composition Provided by',
  'Marketing Promotion',
  'Marketing Strategy',
  'Mastered by',
  'Mastering Engineer',
  'Mixing Engineer',
  'Music Production',
  'OP',
  'Planner',
  'Planner and coordinator',
  'Presented by',
  'Presenter',
  'Produce Company',
  'Produced by',
  'Producer',
  'Production Company',
  'Production Team',
  'Promotion Planning',
  'Promotion Strategy',
  'Propaganda',
  'Published by',
  'Publisher',
  'QQ音乐',
  'Record Producer',
  'Recorded at',
  'Recording Engineer',
  'Recording Studio',
  'Release',
  'Released by',
  'Repertoire Owner',
  'Second Violin',
  'Songs Title',
  'SP',
  'Strings',
  'Strings Arrangement',
  'Supervised production',
  'Viola',
  'Vocal Engineer',
  'Vocal Producer',
  'Vocals by',
  'Vocals Produced by',
  'Words and Music by',
  'Written by',
  '着作权',
  '著作权',
];

const List<String> defaultExcludeRegexes = [
  '(?:【.*?音乐人.*?】|\\(.*?音乐人.*?\\)|「.*?音乐人.*?」|（.*?音乐人.*?）|『.*?音乐人.*?』)',
  '.*?未经.*?不得.*?',
  // QQ音乐版权/翻译声明（含常见变体）
  'QQ音乐.*?(?:着作权|著作权|版权|提供|出品|发行|翻译|享有|独家)',
  // 翻译作品声明（含日语"翻訳"）
  '(?:翻译|本翻译|翻訳|本翻訳).*?(?:作品|版权|着作权|著作权|提供|出品)',
  // 享有/提供 翻译/歌词 声明
  '(?:享有|提供|出品|发行).*?(?:翻译|翻訳|歌词).*?(?:作品|版权|着作权|著作权)?',
  // KRC 首行：曲名 - CJK厂牌名+Records（如 "暁Records"），利用CJK拉丁紧邻特征避免误伤
  // 仅匹配 - CJK文字 Records/Music/... 格式，不会匹配 - Records playing 这类正常歌词
  r'[-－]\s*(?:[\u2e80-\u9fff\u3040-\u309f\u30a0-\u30ff\uac00-\ud7af]+\s*)+(?:Records|records|Music|music)\b',
  // KRC 首行：曲名 - 厂牌 (xxx records/music) 格式（括号包裹的厂牌信息）
  r'[-－].*?\([^)]*(?:records|music|studio|band|project|label|entertainment)[^)]*\)',
];

const List<String> defaultExcludeSoftRegexes = [
  // KRC 首行：标题-歌手分隔符 + 厂牌/音乐相关标签（仅在头部/尾部生效）
  r'[-－]\s*\S*(?:Music|Studio|Band|Project|Label|Entertainment|Official|Records|records)\b',
  // KRC 首行：空格短横空格 分隔模式（标题 - 歌手的典型模式）
  // 结合厂牌关键词由上方 regex 覆盖，此处作为兜底弱匹配
  r'[^\s]+\s*[-－]\s*[^\s]+',
];
