// 元数据剥离关键词表
const List<String> defaultExcludeKeywords = [
  '版权',
  '版权代理',
  '版权方',
  '版权归属',
  '版权公司',
  '版权管理',
  '版权提供',
  '版权运营',
  '贝斯',
  '编曲',
  '策划',
  '唱片公司',
  '唱片厂牌',
  '出品',
  '出品方',
  '出品公司',
  '出品单位',
  '出版',
  '出版方',
  '出版发行',
  '出版公司',
  '出版社',
  '词',
  '大提琴',
  '打击乐',
  '灯光设计',
  '第二小提琴',
  '第一小提琴',
  '电脑工程',
  '额外编程',
  '代理发行',
  '发行',
  '发行方',
  '发行公司',
  '发行机构',
  '发行厂牌',
  '发行单位',
  '翻唱',
  '封面',
  '钢琴/合成器演奏',
  '钢琴演奏',
  '歌名',
  '歌手',
  '艺术家',
  '工作室',
  '鼓',
  '合成器演奏',
  '合声',
  '合声编写',
  '和声',
  '和声编写',
  '和声演唱',
  '和音',
  '混缩',
  '混音',
  '吉他',
  '监制',
  '键盘',
  '乐队统筹',
  '乐队总监',
  '乐器',
  '乐器演奏',
  '乐团',
  '联合策划',
  '联合发行',
  '联合出品',
  '联合推广',
  '录/混音',
  '录音',
  '录音地点',
  '录音师',
  '录音室',
  '录音棚',
  '录音工作室',
  '录音制作',
  '录音版权',
  '录制地点',
  '录制工作室',
  '鸣谢',
  '母带',
  '母带室',
  '母带工作室',
  '配唱制作人',
  '企划',
  '曲',
  '经纪公司',
  '管理公司',
  '混音室',
  '混音棚',
  '混音工作室',
  '设计',
  '数字编辑',
  '数字发行',
  '特别鸣谢',
  '特别企划',
  '题记',
  '统筹',
  '推广',
  '维伴音乐',
  '文案',
  '弦乐',
  '弦乐编写',
  '弦乐监制',
  '弦乐录音师',
  '弦乐录音室',
  '项目统筹',
  '宣传',
  '宣推',
  '演唱',
  '艺术指导',
  '音乐项目总监',
  '音乐发行',
  '音乐厂牌',
  '音乐出版',
  '音乐制作',
  '音乐制作发行',
  '音响总监',
  '音频编辑',
  '音乐编辑',
  '营销推广',
  '词曲版权',
  '独家版权',
  '独家发行',
  '原唱',
  '原曲',
  '制作发行',
  '制作公司',
  '制作单位',
  '制作工作室',
  '制作人',
  '制作统筹',
  '制作团队',
  '制作助理',
  '中提琴',
  '专辑',
  '总策划',
  '总监制',
  '总企划',
  '作词',
  '作曲',
  // 日文
  '詞',
  '訳詞',
  '補作詞',
  '作詞',
  '作曲',
  '編曲',
  '歌',
  '歌唱',
  '演奏',
  'ギター',
  'ベース',
  'ドラム',
  'ピアノ',
  'ストリングス',
  'ホーン',
  'コーラス',
  'ミックス',
  'マスタリング',
  'プロデュース',
  'プロデューサー',
  'レコーディング',
  'レコーディングスタジオ',
  'エンジニア',
  '録音',
  '録音スタジオ',
  '楽器',
  '発売元',
  'レーベル',
  '作編曲',
  '音楽プロデューサー',
  'サウンドプロデューサー',
  'ディレクター',
  'アレンジ',
  // 韩文
  '작사',
  '작곡',
  '편곡',
  '노래',
  '코러스',
  '기타',
  '베이스',
  '드럼',
  '피아노',
  '현악',
  '믹싱',
  '마스터링',
  '프로듀서',
  '녹음',
  '녹음실',
  '악기',
  '발매',
  '배급',
  '유통',
  '레이블',
  '제작',
  '연주',
  '편성',
  '지휘',
  '건반',
  '타악기',
  '관현악',
  '합창',
  // 其他常见语言
  'pgm',
  'Paroles',
  'Musique',
  'Letra',
  'Testo',
  'Acknowledgement',
  'Additional Programming',
  'Additional Vocal by',
  'Arranged By',
  'Arrangement',
  'Arranger',
  'Art Director',
  'Artist',
  'Background Vocals by',
  'Backing Vocal',
  'Backing Vocal Arrangement',
  'Backing Vocals',
  'Backing Vocals Design',
  'Bass',
  'Cello',
  'Chief Producer',
  'Chref Planner',
  'Co-produced by',
  'Co-Producer',
  'Co-production',
  'Composed by',
  'Composer',
  'Copywriting',
  'Copyright Administrator',
  'Copyright Holder',
  'Copyright Management',
  'Copyright Owner',
  'Cover Design',
  'Design',
  'Digital Editing',
  'Distributed by',
  'Distribution',
  'Drums',
  'Executive Producer',
  'Executive Production',
  'First Violin',
  'Guitar',
  'Guitars',
  'Instrument',
  'Instrumentation',
  'Instruments',
  'Jointly Produced by',
  'Label',
  'Lyricist',
  'Lyrics',
  'Lyrics & Composition Provided by',
  'Marketing Promotion',
  'Marketing Strategy',
  'Managed by',
  'Management',
  'Mastered by',
  'Mastered at',
  'Mastering Engineer',
  'Mastering Location',
  'Mastering Studio',
  'Mixed at',
  'Mixing Engineer',
  'Mixing Location',
  'Mixing Studio',
  'Music Production',
  'Music Director',
  'Music Publishing',
  'OP',
  'Percussion',
  'Planner',
  'Planner and coordinator',
  'Presented by',
  'Presenter',
  'Produce Company',
  'Produced by',
  'Producer',
  'Production Company',
  'Production Studio',
  'Production Team',
  'Programming',
  'Promotion Planning',
  'Promotion Strategy',
  'Propaganda',
  'Published by',
  'Publisher',
  'Publishing',
  'Publishing Administrator',
  'Publishing Company',
  'QQ音乐',
  'Record Company',
  'Record Label',
  'Record Producer',
  'Recorded at',
  'Recording Engineer',
  'Recording Location',
  'Recording Studio',
  'Release',
  'Released by',
  'Repertoire Owner',
  'Second Violin',
  'Songs Title',
  'SP',
  'Strings',
  'Strings Arrangement',
  'Supervised production',
  'Sound Engineer',
  'Viola',
  'Vocal',
  'Vocal Engineer',
  'Vocal Producer',
  'Vocals by',
  'Vocals Produced by',
  'Words and Music by',
  'Written by',
  '着作权',
  '著作权',
];

const List<String> defaultExcludeRegexes = [
  '(?:【.*?音乐人.*?】|\\(.*?音乐人.*?\\)|「.*?音乐人.*?」|（.*?音乐人.*?）|『.*?音乐人.*?』)',
  '.*?未经.*?不得.*?',
  // QQ音乐版权/翻译声明（含常见变体）
  'QQ音乐.*?(?:着作权|著作权|版权|提供|出品|发行|翻译|享有|独家)',
  // 翻译作品声明（含日语"翻訳"）
  '(?:翻译|本翻译|翻訳|本翻訳).*?(?:作品|版权|着作权|著作权|提供|出品)',
  // 享有/提供 翻译/歌词 声明
  '(?:享有|提供|出品|发行).*?(?:翻译|翻訳|歌词).*?(?:作品|版权|着作权|著作权)?',
  // 独立出现的公司或出版机构名称，只匹配明确的机构后缀
  r'^[^:：\r\n。！？!?]{1,100}(?:有限责任公司|股份有限公司|有限公司|出版集团|出版集團)$',
  r'^[^:：\r\n。！？!?]{1,80}(?:音乐|音樂|词曲|詞曲|版权|版權)出版$',
  r'^[^:：\r\n.!?]{1,140}(?:Music Publishing(?: Group)?|Publishing (?:Company|Group)|Entertainment Group|Media Group|Records (?:Inc|LLC|Ltd)\.?)$',
  // KRC 首行：曲名 - CJK厂牌名+Records（如 "暁Records"），利用CJK拉丁紧邻特征避免误伤
  // 仅匹配 - CJK文字 Records/Music/... 格式，不会匹配 - Records playing 这类正常歌词
  r'[-－]\s*(?:[\u2e80-\u9fff\u3040-\u309f\u30a0-\u30ff\uac00-\ud7af]+\s*)+(?:Records|records|Music|music)\b',
  // KRC 首行：曲名 - 厂牌 (xxx records/music) 格式（括号包裹的厂牌信息）
  r'[-－].*?\([^)]*(?:records|music|studio|band|project|label|entertainment)[^)]*\)',
  // 作品名+来源标签：(《作品名》TV动画片尾曲/片头曲/主题歌/插曲等)
  r'《[^》]+》.*?(?:TV|アニメ|动画|主題歌|主題曲|主题曲|片头曲|片尾曲|插曲|挿入歌|エンディング|オープニング|エンディングテーマ|オープニングテーマ|主題歌|主題曲)',
  // 括号包裹的动画/影视来源标签
  r'\([^)]*(?:TV|アニメ|动画|主題歌|主題曲|主题曲|片头曲|片尾曲|插曲|挿入歌|エンディング|オープニング)[^)]*\)',
  // 中文括号包裹的动画/影视来源标签
  r'（[^）]*(?:TV|アニメ|动画|主題歌|主題曲|主题曲|片头曲|片尾曲|插曲|挿入歌|エンディング|オープニング)[^）]*）',
  // 行末：- Artist (日文/韩文/中文AltName) 格式
  r'[-－]\s*\S+(?:\s+\S+)*\s*\([^)]*[\u3040-\u309f\u30a0-\u30ff\uac00-\ud7af\u4e00-\u9fff]+[^)]*\)\s*$',
  // 同上，中文括号版
  r'[-－]\s*\S+(?:\s+\S+)*\s*（[^）]*[\u3040-\u309f\u30a0-\u30ff\uac00-\ud7af\u4e00-\u9fff]+[^）]*）\s*$',
];

const List<String> defaultExcludeSoftRegexes = [
  // 简称式机构名需要与其他明确元数据相邻，避免把普通句子当作公司名
  r'^[^:：\r\n。！？!?]{1,80}(?:唱片公司|版权公司|版權公司|出版公司|发行公司|發行公司|经纪公司|經紀公司|管理公司|出品公司|制作公司|宣传公司|宣傳公司|音乐公司|音樂公司|文化公司|传媒公司|傳媒公司|唱片厂牌|唱片廠牌|音乐厂牌|音樂廠牌|发行厂牌|發行廠牌|出版机构|出版機構|发行机构|發行機構|出品单位|出品單位|制作单位|製作單位|发行单位|發行單位)$',
  r'^[^:：\r\n.!?]{1,120}(?:Records|Recordings|Record Label|Music Group|Music Company|Music Publishing|Entertainment|Studios?)$',
  // KRC 首行：标题-歌手分隔符 + 厂牌/音乐相关标签（仅在头部/尾部生效）
  r'[-－]\s*\S*(?:Music|Studio|Band|Project|Label|Entertainment|Official|Records|records)\b',
  // KRC 首行：空格短横空格 分隔模式（标题 - 歌手的典型模式）
  // 结合厂牌关键词由上方 regex 覆盖，此处作为兜底弱匹配
  r'[^\s]+\s*[-－]\s*[^\s]+',
  // 《作品名》—— 书名号内的作品名常作为元数据出现在歌词首尾
  r'《[^》]+》',
  // 包含动画/影视相关关键词
  r'(?:TV|アニメ|动画|主題歌|主題曲|主题曲|片头曲|片尾曲|插曲|挿入歌|エンディング|オープニング)',
  // 歌手名后紧跟括号内的外文名，如 "Cö shu Nie (コシュニエ)"
  r'\S+\s+\([\u3040-\u309f\u30a0-\u30ff\uac00-\ud7af\u4e00-\u9fff]+\)',
  // 同上中文括号版
  r'\S+\s+（[\u3040-\u309f\u30a0-\u30ff\uac00-\ud7af\u4e00-\u9fff]+）',
];
